// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;



namespace Views
{
	public partial class HomeViewController : UIViewController
	{
		LoginViewController login;

		public HomeViewController (IntPtr handle) : base (handle)
		{
			login = Storyboard.InstantiateViewController ("LoginViewController") as LoginViewController;
			
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad ();

			Button.TouchUpInside += (object sender, EventArgs e) => {
				NavigationController.PushViewController(login, true);
			};
		}
	}
}
