// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Views
{
	public partial class MainViewController : UINavigationController
	{
		public MainViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
