// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Views
{
	public partial class MegaMenuViewController : UITableViewController
	{
		public MegaMenuViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
