// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Views
{
	public partial class PasswordViewController : UITableViewController
	{
		public PasswordViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
