// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Views
{
	public partial class UserGalleryViewController : UIViewController
	{
		public UserGalleryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
