// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Views
{
	public partial class UserFeedViewController : UIViewController
	{
		public UserFeedViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
