// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Views
{
	public partial class UserViewController : UIViewController
	{
		public UserViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
